### ISSUE TITLE
Add one or more demos for setting symbol properties

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-lib-viz-leaflet-js#4]
I suggest that you should add one or more demonstrations.  For example call the demo "SymbolBasics: or something like that.  You can always rename and move folders later and split into separate demos if necessary.

Create a Leaflet stand-alone website using simple map and the data that Justin provided.  Because the demos are intended to teach, you should almost over-document via code comments and README.  You always should describe what/why/how so that someone understands the context for the code.

Put the GeoJSON files in a folder "data" under "site" in your demo and read in to display.

One of the goals is to inform Justin and other developers about which Leaflet API calls to make so those developers don't have to research quite so much.  Put links to the original Leaflet documentation.

You can read the map JSON file in a simple way or you can use a subset one one layer and its symbols.

**Comment by smalers** [comment]
Reopen this issue to provide feedback on symbol demos.  My feedback is below.  Some comments are made for the point map and apply to other maps.

General

1. This is a good start but needs to be cleaned up and expanded upon.
2. It would be good to have one or more links to relevant Leaflet documentation.
3. Avoid words that don't add value.  For example, "actual data" should just be "data".
4. Be precise with work meanings to avoid confusion.   For example, `the property "symbol" determines how` is more accurate as `the property "symbol" indicates how...`.

Point-Symbol-Map

1. Code comments:
     1. Documentation is generally good.  Avoid personalized words like "we", "our", etc.  Just say "the map..".
     2. Variables `this_weight`, etc. should probably be `layer_weight`.
     3. It would be more clear if variable names clearly indicated the map configuration file or leaflet, for example, `map_config_layer_symbol_weight` and `leaflet_layer_symbol_weight`.  Variable names should be as long and verbose as necessary for clarity.
     4. We probably need to build up some functions to automate conversion of map configuration file to Leaflet, that we can include in more formal library, for example create a function to convert map configuration color to leaflet color.  The bottom line is that these demos need to clearly map the json config file to Leaflet via naming conventions and functions.
2. Change description to be more informative:  "This map illustrates how to configure symbol properties for point layers, using a JSON map configuration file."
3. The README language should be as specific and direct as possible.  For example, the first sentence should be something like:  This map uses a .json map configuration file to provide information about the map configuration and .geojson point layer files.  Whereas Leaflet defaults to using built-in markers, this demonstration illustrates how to configure symbols using symbol properties such as shape, color, and outline color.
4. Where files are mentioned, indicate their names and if helpful, add a link to the file in the repo using Markdown link syntax.  For example, link to the map project.
5. Need to indicate how to handle as many properties as possible, possibly by adding additional layers.  For example, labeling the map is useful functionality, as is mouse-over text that is formatted from attributes.  Anything that is beyond basic properties can be added as additional issues on the repo and incrementally added.
6. I'm not sure the background on "Point Maps" is helpful given that it is copy and paste from something else.  I think the README should focus on an explanation of how symbols are set for each layer.  For example, use a table to explain how each symbol property in the json file was mapped to a corresponding Leaflet property.  The goal is to help developers quickly understand the relationship between OWF's general map project file and the corresponding Leaflet property.  For example, see below (alphabetize the properties).  Make sure that the items listed match the actual example used.  For example, are colors assigned directly by a color name or rgb value, or is a color table/ramp used?  We need to do more work on color table/ramp.

| **Map Configuration Symbol Property** | **Leaflet Symbol Property** | **Comments** |
| ------ | --------| ----- |
| `color`  | Call Leaflet `abc.xyz()` function on the layer. | Color can be a named color, a hex code, or if a classification, a color table/ramp.|

The above will probably need some explanation of how color values, names, tables are handled.  We will figure out a place for a map configuration document that can be linked to so that background information does not have to be repeated here.  The map configuration file properties will probably evolve over time so the demo will need to be updated.

Polygon-Symbol-Map

1. Change description to e more informative:  "This map illustrates how to configure symbol properties for polygon layers, using a JSON map configuration file."
2. List this after the line demo.  The order of complexity is usually point, line, polygon.
3. See comments above.
4. The demo needs more variability in the map so that the displayed layers illustrate, even to extreme level so that the differences are obvious.  For example, show low and high opacity, narrow and wide outline width.  Different outline color from fill color.
5. The title is inconsistent.  One page says Multipolygon and the other says Polygon.

Line-Symbol-Map

1. Change the name in the gallery from `Line-Map` to `Line-Symbol-Map`.
2. Change description to e more informative:  "This map illustrates how to configure symbol properties for line layers, using a JSON map configuration file."
3. See comments above.
4. Need more layers to show more coverage in properties.  For example, different widths, line ending (rounded, etc.?), outline color, dash-pattern, etc.  Want examples for as many properties as possible.

**Comment by smalers** [comment]
I will spend more time reviewing.  Some initial comments are:

1. Add favicon icon so that viewing the demos shows the OWF logo.
2. Make sure the symbols are consistent with the original data visualization.  For example, drought monitor in the polygons has specific categories that need to be maintained.  Refer to the categories and colors that Kristin has defined for drought monitor.
3. Similarly the use of the colors needs to be striking enough that people don't have to search.  For example, ditch colors aren't showing that much variation. Perhaps switch the drought monitor and ditch classification type?
4. As discussed, use .gitignore to omit the jsDoc output so the repo does not get bloated.  We'll figure out a way to make this happen.

**Comment by smalers** [comment]
The legend should indicate classification value.  For example, in the polygons the legend should include "drought level".  Similarly the legend for ditches say indicate what is being used for classification.  Otherwise, one does not know for sure what the classification applies to.

**Comment by jfilben** [comment]
Added 3 new maps, point-symbol-map, line-symbol-map, polygon-symbol-map each with a detailed README. Addressed all additional comments, Closing issue.
